### ISSUE TITLE
Can't change the number

### ISSUE THREAD

**Issue by jhnrbrt** [anarki-install/Clickbot-Tools-Baby#1]
I want to know how to change the save number in your clickbot, i can't change it, that's why i know the code

**Comment by mcdougelas** [comment]
There's a help button on it

> I want to know how to change the save number in your clickbot, i can't change it, that's why i know the code

**Comment by anarki-install** [comment]
Watch here for the tutorial https://youtu.be/H41DpyySAgo

**Comment by mcdougelas** [comment]
> Watch here for the tutorial https://youtu.be/H41DpyySAgo

Yeah, that better guide there
